### ISSUE TITLE
Can't consume events from PingSource

### ISSUE THREAD

**Issue by mvinkler** [openshift-knative/showcase#27]
How to reproduce:
```
kn service create event-consumer-web --image quay.io/openshift-knative/showcase --scale-min=1
kn source ping create ping-producer --data '{ "value": "Ping" }' --sink ksvc:event-consumer-web
```

This exception is raised for each ping in the user-container log:
```
2023-06-25 18:59:00,491 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (executor-thread-0) Request failed: java.lang.NullPointerException
at java.base/java.util.Objects.requireNonNull(Objects.java:209)
at com.redhat.openshift.knative.showcase.events.Presenter.printData(Presenter.java:102)
at com.redhat.openshift.knative.showcase.events.Presenter.asHumanReadable(Presenter.java:41)
at com.redhat.openshift.knative.showcase.events.Presenter_ClientProxy.asHumanReadable(Unknown Source)
at com.redhat.openshift.knative.showcase.events.Rest.receive(Rest.java:33)
at com.redhat.openshift.knative.showcase.events.Rest.receiveOnIndex(Rest.java:40)
at com.redhat.openshift.knative.showcase.events.Rest_ClientProxy.receiveOnIndex(Unknown Source)
at com.redhat.openshift.knative.showcase.events.Endpoint$quarkusrestinvoker$receiveOnIndex_42942fa85a449e0db59f32cfee1e2510c2300c8b.invoke(Unknown Source)
at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:115)
at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:142)
at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:833
```

**Comment by cardil** [comment]
This fails when the event doesn't have [datacontenttype](https://github.com/cloudevents/spec/blob/main/cloudevents/spec.md#datacontenttype) field. That field is optional, and shouldn't cause the NPE.

**Comment by mvinkler** [comment]
PR: https://github.com/openshift-knative/showcase/pull/29

**Comment by mvinkler** [comment]
Fixed with https://github.com/openshift-knative/showcase/pull/29
